/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import ababan_system.login;
import static ababan_system.regForms.dbemail;
import static ababan_system.regForms.dbusername;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mypc
 */
public class changePass extends javax.swing.JFrame {

    /**
     * Creates new form accountDetails
     */
    public changePass() {
        initComponents();
    }
    
    public boolean duplicateCheck(){
        dbConnector dbc = new dbConnector();
        
        try{
            String query="SELECT*FROM tbl_user  WHERE u_username ='"+Confirmpass.getText()+"'OR u_email = '"+Newpass.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                dbemail = resultSet.getString("u_email");
                if(dbemail.equals(Newpass.getText())){
                    JOptionPane.showMessageDialog(null, "Email is already Used!");
                    Newpass.setText("");
                }
                
               
                dbusername = resultSet.getString("u_username");
                if(dbusername.equals(Confirmpass.getText())){
                    JOptionPane.showMessageDialog(null, "Username is already Used!");
                    Confirmpass.setText("");
                    
                 }  
                return true;  
            }else{
                return false;
            }
            
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserID = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Oldpass = new javax.swing.JTextField();
        Newpass = new javax.swing.JTextField();
        Confirmpass = new javax.swing.JTextField();
        fn = new javax.swing.JLabel();
        fn1 = new javax.swing.JLabel();
        fn2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registrationButton3 = new javax.swing.JButton();
        registrationButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CHANGE PASSWORD");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        LogOutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogOutButton.setText("LOG OUT");
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });
        jPanel4.add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 50));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current User :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 10));

        UserID.setBackground(new java.awt.Color(0, 0, 0));
        UserID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        UserID.setForeground(new java.awt.Color(255, 255, 255));
        UserID.setText("ID");
        jPanel2.add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 10));

        acc_name.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("USER");
        acc_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_nameMouseClicked(evt);
            }
        });
        jPanel2.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 10));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Oldpass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Oldpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(Oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 48));

        Newpass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Newpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewpassActionPerformed(evt);
            }
        });
        jPanel3.add(Newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 47));

        Confirmpass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Confirmpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmpassActionPerformed(evt);
            }
        });
        jPanel3.add(Confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 43));

        fn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fn.setForeground(new java.awt.Color(204, 204, 204));
        fn.setText("Type Old Pass:");
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 10));

        fn1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fn1.setForeground(new java.awt.Color(204, 204, 204));
        fn1.setText("Type New Pass:");
        jPanel3.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 10));

        fn2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fn2.setForeground(new java.awt.Color(204, 204, 204));
        fn2.setText("Comfirm Pass:");
        jPanel3.add(fn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("PASSWORD");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        registrationButton3.setText("Save");
        registrationButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationButton3MouseClicked(evt);
            }
        });
        registrationButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(registrationButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 30));

        registrationButton4.setText("Back");
        registrationButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationButton4MouseClicked(evt);
            }
        });
        registrationButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(registrationButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 400, 370));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewpassActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getIntance();
        acc_name.setText(""+sess.getUname());
        UserID.setText(""+sess.getUid());
        
    }//GEN-LAST:event_formWindowActivated

    private void acc_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_nameMouseClicked

    private void ConfirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmpassActionPerformed

    private void registrationButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationButton3MouseClicked

    private void registrationButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButton3ActionPerformed
        try{
        dbConnector dbc = new dbConnector();
        Session sess = Session.getIntance();
      
        
        String query = "SELECT*FROM tbl_user WHERE u_id ='"+sess.getUid()+"'";
            ResultSet rs = dbc.getData(query);
            if(rs.next()){
                String olddbpass = rs.getString("u_password");
                String oldhash = passwordHasher.hashPassword(Oldpass.getText());
                
                if(olddbpass.equals(oldhash)){
                    String npass = passwordHasher.hashPassword(Newpass.getText());
                    dbc.updateData("UPDATE tbl_user SET u_password = '"+npass+"'");  
                    JOptionPane.showMessageDialog(null, "Successfully Updated");
                    login lg = new login();
                    lg.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Old Password is incorrect!");

                }
                
            }
        
        }catch(SQLException | NoSuchAlgorithmException ex){
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_registrationButton3ActionPerformed

    private void registrationButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationButton4MouseClicked
       accountDetails accd = new accountDetails();
       accd.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_registrationButton4MouseClicked

    private void registrationButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationButton4ActionPerformed

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Confirmpass;
    private javax.swing.JLabel LogOutButton;
    private javax.swing.JTextField Newpass;
    private javax.swing.JTextField Oldpass;
    private javax.swing.JLabel UserID;
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel fn1;
    private javax.swing.JLabel fn2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton registrationButton3;
    private javax.swing.JButton registrationButton4;
    // End of variables declaration//GEN-END:variables
}
