/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ababan_system;

import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mypc
 */
public class regForms extends javax.swing.JFrame {

    /**
     * Creates new form regForm
     */
    public regForms() {
        initComponents();
    }
    public static String dbemail, dbusername;
    
    
    public boolean duplicateCheck(){
        dbConnector dbc = new dbConnector();
        
        try{
            String query="SELECT*FROM tbl_user  WHERE u_username ='"+regUser.getText()+"'OR u_email = '"+regEmail.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                dbemail = resultSet.getString("u_email");
                if(dbemail.equals(regEmail.getText())){
                    JOptionPane.showMessageDialog(null, "Email is already Used!");
                    regEmail.setText("");
                }
                
               
                dbusername = resultSet.getString("u_username");
                if(dbusername.equals(regUser.getText())){
                    JOptionPane.showMessageDialog(null, "Username is already Used!");
                    regUser.setText("");
                    
                 }  
                return true;  
            }else{
                return false;
            }
            
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        regName = new javax.swing.JTextField();
        regEmail = new javax.swing.JTextField();
        regUser = new javax.swing.JTextField();
        registrationButton = new javax.swing.JButton();
        regUserType = new javax.swing.JComboBox<>();
        fn4 = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        fn1 = new javax.swing.JLabel();
        fn2 = new javax.swing.JLabel();
        fn3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regPass = new javax.swing.JPasswordField();
        fn5 = new javax.swing.JLabel();
        regnumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("REGISTRATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(559, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(regName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 30));

        regEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        regEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmailActionPerformed(evt);
            }
        });
        jPanel3.add(regEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, 30));

        regUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        regUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserActionPerformed(evt);
            }
        });
        jPanel3.add(regUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, 30));

        registrationButton.setText("Register");
        registrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationButtonMouseClicked(evt);
            }
        });
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });
        jPanel3.add(registrationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, 35));

        regUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER" }));
        regUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserTypeActionPerformed(evt);
            }
        });
        jPanel3.add(regUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, 30));

        fn4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fn4.setForeground(new java.awt.Color(204, 204, 204));
        fn4.setText("Type:");
        jPanel3.add(fn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 40, 10));

        fn.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fn.setForeground(new java.awt.Color(204, 204, 204));
        fn.setText("Name:");
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, 20));

        fn1.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fn1.setForeground(new java.awt.Color(204, 204, 204));
        fn1.setText("Email:");
        jPanel3.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, 20));

        fn2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fn2.setForeground(new java.awt.Color(204, 204, 204));
        fn2.setText("User:");
        jPanel3.add(fn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, 10));

        fn3.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fn3.setForeground(new java.awt.Color(204, 204, 204));
        fn3.setText("Password:");
        jPanel3.add(fn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 70, 20));

        jLabel2.setText("Registered? Click Here to Login  ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("REGISTER");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        regPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPassActionPerformed(evt);
            }
        });
        jPanel3.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 200, 30));

        fn5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fn5.setForeground(new java.awt.Color(204, 204, 204));
        fn5.setText("Cell Num:");
        jPanel3.add(fn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, 20));

        regnumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        regnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnumberActionPerformed(evt);
            }
        });
        jPanel3.add(regnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 450, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 110));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationButtonMouseClicked

    private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButtonActionPerformed
        if(regName.getText().isEmpty()||regEmail.getText().isEmpty()||regnumber.getText().isEmpty()||regUser.getText().isEmpty()||regPass.getText().isEmpty())
            
        {
            JOptionPane.showMessageDialog(null, "Fill apa ang wa na fill apan duh!");
        }else if(regPass.getText().length()< 8){
            JOptionPane.showMessageDialog(null, "Password character should be 8 above");
            regPass.setText("");

        }else if(duplicateCheck()){
            System.out.println("Duplicate Exist");

        }

        else{
            dbConnector dbc=new dbConnector();
            
            try{
            String pass = passwordHasher.hashPassword(regPass.getText());
            if(dbc.insertData("INSERT INTO tbl_user(u_fname, u_email, u_contact, u_username, u_password, u_status, u_type) "
                + "VALUES('"+regName.getText()+"','"+regEmail.getText()+"','"+regnumber.getText()+"','"+regUser.getText()+"','"+pass+"','pending','"+regUserType.getSelectedItem()+"')"))
        {
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            login lf=new login();
            lf.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Connection Error!");

        }
        } catch(NoSuchAlgorithmException ex){
            System.out.println(""+ex);
        }  
        }      
    }//GEN-LAST:event_registrationButtonActionPerformed

    private void regUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUserTypeActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        login lf=new login();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void regEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailActionPerformed

    private void regPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPassActionPerformed

    private void regUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUserActionPerformed

    private void regnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fn;
    private javax.swing.JLabel fn1;
    private javax.swing.JLabel fn2;
    private javax.swing.JLabel fn3;
    private javax.swing.JLabel fn4;
    private javax.swing.JLabel fn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField regEmail;
    private javax.swing.JTextField regName;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JTextField regUser;
    private javax.swing.JComboBox<String> regUserType;
    private javax.swing.JButton registrationButton;
    private javax.swing.JTextField regnumber;
    // End of variables declaration//GEN-END:variables
}
